/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// It may be overwritten by the router plugin during development/build.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EncuestaRouteImport } from './routes/encuesta'
import { Route as AccesosRouteImport } from './routes/accesos'
import { Route as SalaRouteImport } from './routes/sala'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EncuestaRoute = EncuestaRouteImport.update({
  id: '/encuesta',
  path: '/encuesta',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesosRoute = AccesosRouteImport.update({
  id: '/accesos',
  path: '/accesos',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaRoute = SalaRouteImport.update({
  id: '/sala',
  path: '/sala',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/encuesta': typeof EncuestaRoute
  '/accesos': typeof AccesosRoute
  '/sala': typeof SalaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/encuesta': typeof EncuestaRoute
  '/accesos': typeof AccesosRoute
  '/sala': typeof SalaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/encuesta': typeof EncuestaRoute
  '/accesos': typeof AccesosRoute
  '/sala': typeof SalaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/encuesta' | '/accesos' | '/sala'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/encuesta' | '/accesos' | '/sala'
  id: '__root__' | '/' | '/admin' | '/encuesta' | '/accesos' | '/sala'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EncuestaRoute: typeof EncuestaRoute
  AccesosRoute: typeof AccesosRoute
  SalaRoute: typeof SalaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport }
    '/encuesta': { id: '/encuesta'; path: '/encuesta'; fullPath: '/encuesta'; preLoaderRoute: typeof EncuestaRouteImport; parentRoute: typeof rootRouteImport }
    '/accesos': { id: '/accesos'; path: '/accesos'; fullPath: '/accesos'; preLoaderRoute: typeof AccesosRouteImport; parentRoute: typeof rootRouteImport }
    '/sala': { id: '/sala'; path: '/sala'; fullPath: '/sala'; preLoaderRoute: typeof SalaRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AdminRoute,
  EncuestaRoute,
  AccesosRoute,
  SalaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
